<main class="p-5">
    <h1>
        Page d'accueil
    </h1>
   
   <?php foreach($categories as $category){ ?>
       <section class="my-4">
            <h2>
                <?= $category["name"] ?>
            </h2>
            <ul class="row g-3 p-0" style="list-style:none;">
                <?php foreach($category["posts"] as $post){ ?>
                    <li class="col-3">
                        <article class="card pb-4">
                            <img src="<?= $post["url"] ?>" class="card-img-top" alt="<?= $post["alt"] ?>">
                            <h3 class="card-title px-2 my-3" style="min-height:6rem;">
                                <?= $post["title"] ?>
                            </h3>
                            <a href="index.php?route=post&post=<?= $post["id"] ?>" class="btn btn-primary mx-2">Lire l'article</a>
                        </article>
                    </li>
                <?php } ?>
            </ul>
        </section>
   <?php } ?>
</main>