<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="utf8">
        <title>Blog Développement Web</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    </head>
    <body class="container-fluid p-0">
        <header class="navbar navbar-expand-lg bg-primary px-5">
            <nav class="container-fluid p-0">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link text-light" aria-current="page" href="index.php">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-light" href="index.php?route=category&category=1">Frontend</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-light" href="index.php?route=category&category=2">Backend</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-light" href="index.php?route=category&category=3">Intégration</a>
                    </li>
                </ul>
            </nav>
        </header>
        <?php require $template; ?>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    </body>
</html>